== AeroGear Unified Push Server Integration Tests image:https://travis-ci.org/aerogear/aerogear-unifiedpush-server-integration-tests.svg?branch=master["Build Status", link="https://travis-ci.org/aerogear/aerogear-unifiedpush-server-integration-tests"]

This project contains the integration tests and functional tests for the https://github.com/aerogear/aerogear-unified-push-server[Aerogear UnifiedPush Server] project.

== Integration Tests Content

Each Test defines the three core aspects needed for the execution of an http://arquillian.org/[Arquillian] test case:

- container — the runtime environment
- deployment — the process of dispatching an artifact to a container
- archive — a packaged assembly of code, configuration and resources

The container's configuration resides in the link:src/test/resources/arquillian.xml[arquillian.xml] configuration file while the deployment 
and archives are defined in the link:src/test/java/org/jboss/aerogear/unifiedpush/test/Deployments.java[Deployments.java] file.

The test case is dispatched to the container's environment through coordination with ShrinkWrap, which is used to declaratively define a custom archive that encapsulates the test class and its dependent resources. Arquillian packages the ShrinkWrap defined archive at runtime and deploys it to the target container. It then negotiates the execution of the test methods and captures the test results using remote communication with the server. Finally, Arquillian undeploys the test archive.

== Execution
Navigate to the project's root folder and execute:

    ./setup/setup.sh

This step does the following:

* Grabs AS 7.1.1 and WildFly 8.1.0 installations from jboss.org site
* Adds HTTPS connector to server configuration (both AS and WildFly)
* Clones repository of aerogear-unifiedpush-server into aerogear-unifiedpush-server directory

Navigate to the project's root folder and setup the `JBOSS_HOME` environment variable:

    export JBOSS_HOME=`pwd`/jboss-as-7.1.1.Final

NOTE: If you wish to run the tests against WildFly, export this instead and then activate WildFly profiles:
+    
    export JBOSS_HOME=`pwd`/wildfly-8.1.0.Final

The integration tests execution is done through Maven. Navigate to the project's root folder and execute:

    mvn test

NOTE: This will activate default profiles (JBoss AS7 and local deployment).

=== Additional configuration

You can specify additional profiles and properties to fine grain what you want to run and where.

.Unified Push Server location
|====
| _Type_ | _Activation_ | _Description_

| local | +-Ptest-local+ , by default | Uses local file system location to build UPS from sources.
You can additionally specify the location by using +-Dups.local.pom+

| release | +-Ptest-release+ | Uses Maven repository to grab latest UnifiedPush Server and Auth WAR available there. You can use
+-Dups.remote.url+ to specify the repository and +-Dups.version+ to grab particular version

| staging | +-Ptest-staging+ | The same as _release_ but uses staging repository on JBoss Nexus by default

| archive | +-Ptest-archive+ | Uses pre-built WARs to be deployed. You _must_ specify path via +-Dups.server.archive.path=/path/to/ups.war+
and +-Dups.auth.archive.path=/path/to/auth.war+.

|====

.Containers
[width=60%]
|====
| _Type_ | _Activation_
| JBoss AS7 | +-Pas711-managed+ (by default)
| JBoss AS7 domain mode | +-Pas711-domain-managed+
| JBoss EAP6 | +-Peap6-managed+
| JBoss EAP6 domain mode | +-Peap6-domain-managed+
| WildFly | +-Pwildfly-managed+
| WildFly domain mode | +-Pwildfly-domain-managed+
|====

 
=== JUnit Categories

You can select particular tests to be excluded or included in the testsuite. You should use +-Dgroups=+ to define comma separated
list of groups that will be executed and +-DexcludedGroups=+ to define comma separated list of groups that won't be executed.

Exclusion list has the priority in case one test is annotated via multiple categories. Following categories are defined:

* category.AdminUI - _disabled_ by default
* category.ChromePackagedApp - enabled by default
* category.NotIPv6Ready - enabled by default
* category.Performance - _disabled_ by default
* category.SimplePush - enabled by default
* (no category) - default integration test, enabled by default

=== Browser Selection

You can select browser to be used to run Admin UI tests via +-Dbrowser=value+. Values are compatible with Arquillian Drone.

Example that executes Admin UI tests on Firefox:
    
    mvn test -Dgroups=category.AdminUi -Dbrowser=firefox

== Additional Documentation

*  http://arquillian.org/guides/[Arquillian Guides]
